# [作業目標]

1. [簡答題] 請問 type(...) 跟 a.dtype 這兩個語法有什麼不同？

```
print('type(a): ', type(a))
print('a.dtype: ', a.dtype)
```

2. 請撰寫一個判斷 a 的元素是否等於指定資料型態的函式

3. [簡答題] 承上題，請判斷下列三種寫法為何不正確？

```
def is_dtype(a, t):
    return a.dtype is t

def is_dtype(a, t):
    return type(a) == np.dtype(t)

def is_dtype(a, t):
    return type(a) is np.dtype(t)
```

In [1]:
import numpy as np
print('Numpy Version: ', np.__version__)

Numpy Version:  1.20.3


# 作業 

### 1. [簡答題] 請問 type(...) 跟 a.dtype 這兩個語法有什麼不同？

```
print('type(a): ', type(a))
print('a.dtype: ', a.dtype)
```


In [2]:
a = np.linspace(2, 10, num=6, endpoint=True, dtype='int64')
print(a)
print('type(a): ', type(a))
print('a.dtype: ', a.dtype)

[ 2  3  5  6  8 10]
type(a):  <class 'numpy.ndarray'>
a.dtype:  int64


type() 是檢查變數的型態，而不是元素的型態
- type()：回傳變數(a)的型態
- dtype()：回傳陣列(a)中的元素型態

### 2. 請撰寫一個判斷 a 的元素是否等於指定資料型態的函式，並且通過測試。



In [3]:
# 記得先 Import 正確的套件

In [4]:
def is_dtype(a, t):
    return a.dtype is np.dtype(t)
print(a)
print(is_dtype(a, "int64"))


[ 2  3  5  6  8 10]
True


In [5]:
a = np.random.randint(10, size=6) 

# 測試一
print(is_dtype(a, 'int')) # True

# 測試二
print(is_dtype(a, np.int)) # True

# 測試三
print(is_dtype(a, np.dtype('int'))) # True

True
True
True


<ipython-input-5-6b731107c1a5>:7: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  print(is_dtype(a, np.int)) # True


### 3. [簡答題] 承上題，請判斷下列三種寫法為何不正確？

In [9]:
def is_dtype(a, t):
    return a.dtype is t
print(a)
print(is_dtype(a, "int64"))
# is是強比較，兩邊的物件型態也要相同，左邊是 np.type而右邊不一定是，因此不正確

def is_dtype(a, t):
    return type(a) == np.dtype(t)
print(a)
print(is_dtype(a, "int64"))
# type()是回傳陣列的型態(numpy.ndarray)；而 np.dtype()是回傳陣列中元素的型態

def is_dtype(a, t):
    return type(a) is np.dtype(t)
print(a)
print(is_dtype(a, "int64"))
# 同上題，兩者回傳的型態不同，更加不能用 is強比較去判定

[4 2 7 4 2 4]
False
[4 2 7 4 2 4]
False
[4 2 7 4 2 4]
False
