# [作業目標]

1. [簡答題] 請問下列程式碼，運算結果分別為何？

```
a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] ) 
c = 1
d = np.array( [1] )
e = np.array( [1,2] ) 
```

2. 如何在不用迴圈的情況下計算 (A+B)*(-A/2) ？那用迴圈怎麼做？

3. 請問如何計算「1x6 的單位矩陣」和「6x1 的單位矩陣」的內積和外積？

# 作業 

### 1. [簡答題] 請問下列程式碼，運算結果分別為何？

```
a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] ) 
c = 1
d = np.array( [1] )
e = np.array( [1,2] ) 
```


In [1]:
import numpy as np
a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] ) 
c = 1
d = np.array( [1] )
e = np.array( [1,2] ) 

In [2]:
print(a + a)
print(a + b)
print(a + c)
print(a + d)
print(a + e)

[ 40  60  80 100]
[21 32 43 54]
[21 31 41 51]
[21 31 41 51]


ValueError: operands could not be broadcast together with shapes (4,) (2,) 

### 2. 如何在不用迴圈的情況下計算 (A+B)*(-A/2) ？那用迴圈怎麼做？


In [3]:
# 記得先 Import 正確的套件

import numpy as np


In [4]:
A = np.ones(3)*1
B = np.ones(3)*2

print((A+B)*(-A/2))

C = np.empty(3)
for i in range(3):
    C[i] = (A[i]+B[i])*(-A[i]/2)
print(C)

print("------------------")
c=[]
for i,array_a in enumerate(A):
    c.append( (A[i] + B[i]) * ((-1*A[i])/2) )
print(c)

[-1.5 -1.5 -1.5]
[-1.5 -1.5 -1.5]
------------------
[-1.5, -1.5, -1.5]


### 3. 請問如何計算「1x6 的單位矩陣」和「6x1 的單位矩陣」的內積和外積？


In [5]:
A = np.ones((1,6))
B = np.ones((6,1))
print(A)
print(B)
print()
print(A@B)
# 如果a和b都是二維數組，則是矩陣乘法，但首選使用matmul或。a@b
# print(np.dot(A,B))
print()
print(A * B)
# print(np.outer(A,B))

[[1. 1. 1. 1. 1. 1.]]
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]

[[6.]]

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
