# 範例
***

# [教學目標]

* 能夠使用不同的方法初始化一個陣列
* 知道固定大小對於陣列的意義
* 了解不同的亂數陣列有什麼差異



In [1]:
# 載入 NumPy 套件
import numpy as np

# 檢查正確載入與版本
print(np)
print(np.__version__)

<module 'numpy' from '/Users/shuwn/opt/anaconda3/lib/python3.8/site-packages/numpy/__init__.py'>
1.20.3


In [2]:
# 內建型態做轉換
import numpy as np

np.array([1, 2, 3])

array([1, 2, 3])

In [3]:
# 會自動轉換成範圍比較大的型態：
print(np.array([1, 2, 3.0]), np.array([1, 2, 3.0]).dtype)

print()
# 也可以指定成想要的型態：
print(np.array([1, 2, 3], dtype=complex), np.array([1, 2, 3], dtype=complex).dtype)

[1. 2. 3.] float64

[1.+0.j 2.+0.j 3.+0.j] complex128


In [4]:
# 字典型態被轉成陣列不符合期待
print(np.array({0: 123, 1: 456}))
print(np.array({0: 123, 1: 456}).size)

print()

# 正確的寫法應該寫轉成有序的 List 再作轉換
print(list({0: 123, 1:456}))
print(list({0: 123, 1:456}.items()))
print(np.array(list({0: 123, 1: 456}.items())))
print(np.array(list({0: 123, 1: 456}.items())).size)

{0: 123, 1: 456}
1

[0, 1]
[(0, 123), (1, 456)]
[[  0 123]
 [  1 456]]
4


In [5]:
# 從固定大小的初始值開始
# 建立由 0 組成的 2x3 陣列
print(np.zeros((2, 3)))
print()

# 建立由 1 組成的 2x3 陣列
print(np.ones((2, 3)))
print()

# 建立由 9 組成的 2x3 陣列
print(np.full((2, 3), 9))


[[0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]]

[[9 9 9]
 [9 9 9]]


In [15]:
# np.zeros 和 np.empty 

print(np.zeros((2, 3)), end="\n"*2)
print()
print(np.empty((2, 3)))


[[0. 0. 0.]
 [0. 0. 0.]]


[[0. 0. 0.]
 [0. 0. 0.]]


In [19]:
# 從固定大小的序列值開始
print("固定長度的等差序列:", np.arange( 10, 30, 5 ))
print()
print("固定區間的等差序列:", np.linspace( 0, 5, 3 ))
print()
print("等比序列:", np.logspace( 0, 2, 5 ))


固定長度的等差序列: [10 15 20 25]

固定區間的等差序列: [0.  2.5 5. ]

等比序列: [  1.           3.16227766  10.          31.6227766  100.        ]


In [21]:
## 從固定大小的亂數值開始（新版）

from numpy.random import default_rng
rng = default_rng()

normal = rng.standard_normal((3,2))
random = rng.random((3,2))
integers = rng.integers(0, 10, size=(3,2))

print("亂數常態分佈\n", normal)
print()
print("亂數\n", random)
print()
print("整數\n", integers)

亂數常態分佈
 [[ 0.65936986  0.21452037]
 [ 0.63735308 -0.77712079]
 [ 1.47869658  0.52706329]]

亂數
 [[0.52114889 0.07956044]
 [0.04111862 0.67363603]
 [0.07687926 0.85069017]]

整數
 [[8 3]
 [1 0]
 [3 1]]


In [9]:
## 從固定大小的亂數值開始（舊版）

normal = np.random.randn(3, 2)
random = np.random.random((3,2))
integers = np.random.randint(0, 10, size=(3,2))

print(normal)
print()
print(random)
print()
print(integers)

[[ 0.53704567  0.32855439]
 [-0.93953405  0.01833321]
 [ 0.13530439  0.82336005]]

[[0.21820832 0.65286311]
 [0.24532807 0.05011897]
 [0.59286267 0.261083  ]]

[[6 6]
 [6 3]
 [1 0]]
