# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

In [1]:
import numpy as np
print(np.__version__)

1.20.3


# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


In [2]:
print(np.zeros((2, 3)))
print(np.empty((2, 3)))

[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]


- np.zeros得出的data是唯一真0的數值，而np.empty得出的data唯一非常接近0的數值
- empty所得出的是隨機值，且速度較快。zeros速度較慢，且有指定
>np.empry 可用於產生一個初始值不重要的空陣列

### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [3]:
# 記得先 Import 正確的套件
import numpy as np
print(np.__version__)

1.20.3


In [8]:
# 參考解答

a = np.random.rand(2, 3)

print(a)
print("四捨五入", a.round())
print("-------------")

b = np.random.rand(2, 3)*100
print("四捨五入", b.round())


[[0.93136719 0.27921973 0.54446705]
 [0.22179683 0.17630236 0.79758611]]
四捨五入 [[1. 0. 1.]
 [0. 0. 1.]]
-------------
四捨五入 [[31.  5. 86.]
 [50. 90. 46.]]


### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [11]:
m = 20
n = 40

a = np.random.rand(2, 3)
b = np.random.randint(m, n, (2, 3))
# random.randint(low, hight) -> 返回一個位於[low,hight]之間的整數

print(a)
print(b)

[[0.84736504 0.40430936 0.28276909]
 [0.97006587 0.42860096 0.73521758]]
[[30 24 33]
 [36 20 31]]
