# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

In [1]:
import numpy as np
a = np.arange(15).reshape(3, 5)
print(a)
print(type(a))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
<class 'numpy.ndarray'>


### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [2]:
print('list(a): ', list(a))
print('tolist(): ', a.tolist())

list(a):  [array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14])]
tolist():  [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]


##List(a)
只會把第一層元素轉化為 List

##tolist
能轉換多層的型態

### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [3]:
# 記得先 Import 正確的套件

In [4]:
# 一維陣列
a = np.random.randint(10, size=6)
print(a)
print(type(a))

#二維陣列
b = np.random.randint(10, size=(3,4))
print(b)
print(type(b))

#三維陣列
c = np.random.randint(10, size=(2,3,2)) 
print(c)
print(type(c))

print(c.ndim) #陣列有多少維度
print(c.shape) #每個維度的大小
print(c.size) #陣列當中有幾個元素
print(c.dtype) #陣列中的資料型態
print(c.itemsize) #陣列中每個元素佔用的空間
print(c.data) #陣列所存在的記憶體位置

[2 6 4 0 9 4]
<class 'numpy.ndarray'>
[[1 6 6 5]
 [6 0 4 9]
 [3 1 6 2]]
<class 'numpy.ndarray'>
[[[9 5]
  [3 2]
  [7 5]]

 [[2 2]
  [1 5]
  [5 1]]]
<class 'numpy.ndarray'>
3
(2, 3, 2)
12
int64
8


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [5]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


[4, 9, 2, 2, 9, 2]
[4, 9, 2, 2, 9, 2]


In [6]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


[[6, 3, 3, 6], [6, 9, 6, 4], [6, 6, 0, 8]]
[array([6, 3, 3, 6]), array([6, 9, 6, 4]), array([6, 6, 0, 8])]


In [7]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[[[2, 2], [8, 2], [3, 8]], [[7, 7], [4, 6], [2, 2]]]
[array([[2, 2],
       [8, 2],
       [3, 8]]), array([[7, 7],
       [4, 6],
       [2, 2]])]


In [8]:
# 傳入的參數個數可變，可以為0到任意個。在參數前加*實現可變參數。 可變參數在函數調用時自動組裝為一個tuple。
# 在列表和元組前加*，可以將列表或元組中的元素變為可變參數傳入函數。
def tolist(*iterable):
    for i in iterable:
        return i.tolist()

print(tolist(a))
print(tolist(b))
print(tolist(c))

[4, 9, 2, 2, 9, 2]
[[6, 3, 3, 6], [6, 9, 6, 4], [6, 6, 0, 8]]
[[[2, 2], [8, 2], [3, 8]], [[7, 7], [4, 6], [2, 2]]]
