In [1]:
import numpy as np

In [2]:
print(np)
print(np.__version__)

<module 'numpy' from '/Users/shuwn/opt/anaconda3/lib/python3.8/site-packages/numpy/__init__.py'>
1.19.2


In [3]:
import numpy as np
a = np.arange(15).reshape(3, 5)
print(a)
# array([[ 0,  1,  2,  3,  4],
#        [ 5,  6,  7,  8,  9],
#        [10, 11, 12, 13, 14]])

print(type(a)) # <type 'numpy.ndarray'>

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
<class 'numpy.ndarray'>


In [5]:
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(a.data)

2
(3, 5)
15
int64
8
